/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Members;

import Core.ObjectParser;
import Models.Member;
import Models.SetOfBooks;
import Models.SetOfMembers;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sithira
 */
public class MembersGUI extends javax.swing.JFrame {

    private ObjectParser parser = ObjectParser.getInstance();

    DefaultTableModel tableModel = null;

    String columnNames[] = {"Member ID", "Member Name", "Set of Books"};

    /**
     * Creates new form MembersGUI
     */
    public MembersGUI() {
      
        initComponents();
        
        tableModel = new DefaultTableModel(columnNames, 0);

        try {

            //clearTable();
            Object som = parser.readObject(SetOfMembers.TABLE_PATH);

            loadDataToTable(som);

        } catch (IOException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_member_frame = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        member_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lbl_member_name = new javax.swing.JLabel();
        member_id = new javax.swing.JTextField();
        member_name = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        btn_add_member = new javax.swing.JButton();
        btn_reload_table = new javax.swing.JButton();
        member_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        label_member_frame.setFont(new java.awt.Font("Monaco", 0, 24)); // NOI18N
        label_member_frame.setText("LMS Members");

        member_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(member_table);

        jLabel1.setText("Member ID : ");

        lbl_member_name.setText("Member Name : ");

        search_button.setText("Search");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        btn_add_member.setText("Add a new member");
        btn_add_member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_memberActionPerformed(evt);
            }
        });

        btn_reload_table.setText("Reload Table");
        btn_reload_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reload_tableActionPerformed(evt);
            }
        });

        member_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/images/users.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btn_add_member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reload_table))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_member_name)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(member_id)
                            .addComponent(member_name, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(member_img)
                .addGap(42, 42, 42)
                .addComponent(label_member_frame)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(label_member_frame))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(member_img)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(member_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_member_name)
                            .addComponent(member_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(search_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_reload_table)
                    .addComponent(btn_add_member))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_memberActionPerformed

        (new AddMemberGUI()).setVisible(true);

        dispose();

    }//GEN-LAST:event_btn_add_memberActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed

        clearTable();
        
        try {
            SetOfMembers somp = (SetOfMembers) parser.readObject(SetOfMembers.TABLE_PATH);

            SetOfMembers som = new SetOfMembers();
            
            if (!member_id.getText().isEmpty()) {

                

                Member member = somp.getMemberFromNumber(Integer.parseInt(member_id.getText()));
                
                som.addMember(member);
                
                loadDataToTable(som);

            } else {

                if (!member_name.getText().isEmpty()) {
                   
                    som = somp.getMembersFromName(member_name.getText());

                    loadDataToTable(som);
                    
                }

            }

        } catch (IOException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_search_buttonActionPerformed

    private void btn_reload_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reload_tableActionPerformed

        clearTable();

        try {
            
            SetOfMembers som = (SetOfMembers) parser.readObject(SetOfMembers.TABLE_PATH);

            loadDataToTable(som);
        } catch (IOException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MembersGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_reload_tableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MembersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MembersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MembersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MembersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MembersGUI().setVisible(true);
            }
        });
    }

    private void loadDataToTable(Object param) throws IOException,
            FileNotFoundException,
            ClassNotFoundException {

        SetOfMembers som = new SetOfMembers();

        Object somo = param;

        final SetOfMembers soped = (SetOfMembers) somo;

        member_table.setModel(tableModel);

        member_table.setCellSelectionEnabled(false);

        for (Member member : soped.getMembers()) {

            String member_name = "N/A";

            if (member.getName() != null) {
                member_name = member.getName();
            }

            final SetOfBooks books;

            StringBuilder booknames = new StringBuilder();

            if (member.getBooksOnLoan() != null) {
                books = member.getBooksOnLoan();

                if (books.getBooks() != null && books.getBooks().size() > 0) {

                    int bookSize = books.getBooks().size();

                    for (int x = 0; x < bookSize; x++) {

                        booknames.append(books.getBooks().get(x).getTitle());

                        if (x + 1 != bookSize) {
                            booknames.append(", ");
                        }
                    }

                }

            }

            Object row[] = {
                member.getMemberNumber(),
                member_name,
                booknames.toString()
            };

            tableModel.addRow(row);
        }

        member_table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = member_table.rowAtPoint(evt.getPoint());
                int col = member_table.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {

                    String member_name = member_table
                            .getValueAt(row, 0)
                            .toString();

                    Member member = soped.getAMemberFromName(member_name);

                    boolean opened = false;

//                        for (Book book : setOfMembers.getBooks())
//                        {                                       
//                            (new UpdateBookGUI(book)).setVisible(true);
//
//                            opened = true;
//                        }
                    if (opened) {
                        dispose();
                    }

                }
            }
        });

    }

    private void clearTable() {

        tableModel.getDataVector().removeAllElements();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_member;
    private javax.swing.JButton btn_reload_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_member_frame;
    private javax.swing.JLabel lbl_member_name;
    private javax.swing.JTextField member_id;
    private javax.swing.JLabel member_img;
    private javax.swing.JTextField member_name;
    private javax.swing.JTable member_table;
    private javax.swing.JButton search_button;
    // End of variables declaration//GEN-END:variables
}
